from __future__ import annotations

import subprocess

import pytest

from rosettakit import tcl
from rosettakit.errors import UnsafeRawError, ValidationError
from tests.tclsh_utils import require_tclsh


def test_tcl_script_builds_global_var_like_document() -> None:
    script = tcl.Script()
    script.comment("Auto-generated by RosettaKit")
    script.set("top_design", tcl.word("gcd_core"))
    script.set("clk_freq_mhz", 500)
    script.set_path("final_netlist_file", "build out/gcd final.v")
    script.set_list("lib_list", ["libs/fast corner.lib", "libs/slow.lib"])
    script.set_expr("clk_period_ps", "1000000.0 / $clk_freq_mhz")
    script.set_path("tmp_dir", "build out/tmp")
    script.file_mkdir(tcl.var("tmp_dir"))
    script.set_path("synth_stat_json", "reports/synth stat.json")
    script.set("stat_dir", tcl.call("file", "dirname", tcl.var("synth_stat_json")))

    with script.if_not(tcl.file_isdirectory(tcl.var("stat_dir"))):
        script.file_mkdir(tcl.var("stat_dir"))

    assert script.build() == (
        "# Auto-generated by RosettaKit\n"
        "set top_design gcd_core\n"
        "set clk_freq_mhz 500\n"
        "set final_netlist_file {build out/gcd final.v}\n"
        "set lib_list [list {libs/fast corner.lib} libs/slow.lib]\n"
        "set clk_period_ps [expr {1000000.0 / $clk_freq_mhz}]\n"
        "set tmp_dir {build out/tmp}\n"
        "file mkdir $tmp_dir\n"
        "set synth_stat_json {reports/synth stat.json}\n"
        "set stat_dir [file dirname $synth_stat_json]\n"
        "if {!([file isdirectory $stat_dir])} {\n"
        "    file mkdir $stat_dir\n"
        "}\n"
    )


def test_tcl_quoting_covers_special_characters() -> None:
    script = tcl.Script()
    script.set("space", "a b")
    script.set("braces", "a}b")
    script.set("dollar", "cost $5")
    script.set("bracket", "pin[0]")
    script.set("quote", 'a"b')
    script.set("backslash", r"a\b")
    script.set("empty", "")

    assert script.build() == (
        "set space {a b}\n"
        "set braces a\\}b\n"
        "set dollar {cost $5}\n"
        "set bracket {pin[0]}\n"
        "set quote {a\"b}\n"
        "set backslash {a\\b}\n"
        "set empty {}\n"
    )


def test_tcl_quoting_escapes_unbraceable_words_without_extra_lines() -> None:
    script = tcl.Script()
    script.set("left_brace", "a{b")
    script.set("newline", "a\nputs BAD")
    script.set("semicolon", "a;puts BAD}")

    text = script.build()

    assert text == (
        "set left_brace a\\{b\n"
        "set newline a\\nputs\\ BAD\n"
        "set semicolon a\\;puts\\ BAD\\}\n"
    )


def test_tcl_multiline_comments_prefix_every_line() -> None:
    script = tcl.Script()
    script.comment("note\nputs BAD")

    assert script.build() == "# note\n# puts BAD\n"


def test_tcl_comments_escape_block_sensitive_characters() -> None:
    script = tcl.Script()

    with script.if_not(tcl.Condition("0")):
        script.comment("}")
        script.comment("trailing\\")
        script.set("ok", 1)

    text = script.build()

    assert text == (
        "if {!(0)} {\n"
        "    # \\}\n"
        "    # trailing\\\\\n"
        "    set ok 1\n"
        "}\n"
    )
    result = subprocess.run(
        [require_tclsh()],
        input=text + "puts $ok\n",
        check=True,
        capture_output=True,
        text=True,
    )
    assert result.stdout == "1\n"


def test_tcl_if_not_negates_composite_conditions() -> None:
    script = tcl.Script()

    with script.if_not(tcl.Condition("$a || $b")):
        script.set("result", "false")

    assert script.build() == "if {!($a || $b)} {\n    set result false\n}\n"


def test_tcl_validate_reports_contextual_diagnostics() -> None:
    script = tcl.Script()
    script.set_path("bad_path", "", origin="unit.empty_path")
    script.raw_line("puts $untrusted", origin="unit.raw")
    script.set("bad_list", tcl.list_value(["a", "b"]), origin="unit.list")

    diagnostics = script.validate()

    assert [(item.code, item.origin) for item in diagnostics] == [
        ("empty-path", "unit.empty_path"),
        ("unsafe-raw", "unit.raw"),
        ("list-through-scalar-api", "unit.list"),
    ]


def test_tcl_raw_values_are_unsafe_by_default() -> None:
    script = tcl.Script()
    script.set("now", tcl.raw("[clock seconds]"), origin="unit.raw_value")

    assert [(item.code, item.origin) for item in script.validate()] == [
        ("unsafe-raw", "unit.raw_value"),
    ]
    with pytest.raises(UnsafeRawError, match="unit.raw_value"):
        script.build()
    assert script.build(allow_unsafe_raw=True) == "set now [clock seconds]\n"


def test_tcl_raw_values_in_conditions_are_unsafe_by_default() -> None:
    script = tcl.Script()

    with script.if_not(tcl.file_isdirectory(tcl.raw("$unsafe")), origin="unit.raw_condition"):
        script.set("ok", 1)

    assert [(item.code, item.origin) for item in script.validate()] == [
        ("unsafe-raw", "unit.raw_condition"),
    ]
    with pytest.raises(UnsafeRawError, match="unit.raw_condition"):
        script.build()
    assert script.build(allow_unsafe_raw=True) == (
        "if {!([file isdirectory $unsafe])} {\n"
        "    set ok 1\n"
        "}\n"
    )


def test_tcl_builder_can_build_script_directly() -> None:
    script = tcl.Script()
    script.set("top_design", "gcd")

    assert script.nodes == (tcl.Set("top_design", tcl.Scalar("gcd")),)
    assert tcl.TclBuilder().build(script) == "set top_design gcd\n"


def test_tcl_build_fails_for_invalid_or_unsafe_documents() -> None:
    invalid = tcl.Script()
    invalid.set("", "value", origin="unit.empty_name")
    with pytest.raises(ValidationError, match="tcl"):
        invalid.build()

    unsafe = tcl.Script()
    unsafe.raw_line("puts $untrusted", origin="unit.raw")
    with pytest.raises(UnsafeRawError, match="unit.raw"):
        unsafe.build()

    assert unsafe.build(allow_unsafe_raw=True) == "puts $untrusted\n"
