from __future__ import annotations

from pathlib import Path
import subprocess

from examples import sizer_cmd_file, sizer_env_file, yosys_global_var
from tests.tclsh_utils import require_tclsh


def test_yosys_example_output_is_deterministic_and_tclsh_valid(tmp_path: Path) -> None:
    text = yosys_global_var.build_global_var_tcl()

    assert text == (
        "# Auto-generated by RosettaKit\n"
        "set top_design gcd_core\n"
        "set clk_freq_mhz 500\n"
        "set final_netlist_file {build out/gcd final.v}\n"
        "set lib_list [list {libs/fast corner.lib} libs/slow.lib]\n"
        "set clk_period_ps [expr {1000000.0 / $clk_freq_mhz}]\n"
        "set tmp_dir {build out/tmp}\n"
        "file mkdir $tmp_dir\n"
        "set synth_stat_json {reports/synth stat.json}\n"
        "set stat_dir [file dirname $synth_stat_json]\n"
        "if {!([file isdirectory $stat_dir])} {\n"
        "    file mkdir $stat_dir\n"
        "}\n"
    )

    script_path = tmp_path / "global_var.tcl"
    script_path.write_text(text, encoding="utf-8")
    subprocess.run([require_tclsh(), str(script_path)], check=True, cwd=tmp_path)


def test_sizer_examples_are_deterministic() -> None:
    assert sizer_cmd_file.build_cmd_file() == (
        "-useOpenSTA\n"
        "-top gcd_core\n"
        "-def {build out/input.def}\n"
        "-sdc {constraints/main clock.sdc}\n"
        "-lef tech/sky130.lef\n"
        "-lef {macro lef/sram.lef}\n"
        "-lib lib/slow.lib\n"
        "-lib {lib/fast corner.lib}\n"
        "-outputPath .\n"
        "-def_out_path out/final.def\n"
    )
    assert sizer_env_file.build_env_file() == (
        "# Sizer environment\n"
        "set_db {design_process_node 130}\n"
        "\n"
        "set_db {design_netlist_file build/gcd.v}\n"
    )
