from __future__ import annotations

import pytest

from rosettakit import tcl
from rosettakit.errors import UnsafeRawError, ValidationError


def test_tcl_script_builds_global_var_like_document() -> None:
    script = tcl.Script()
    script.comment("Auto-generated by RosettaKit")
    script.set("top_design", tcl.word("gcd_core"))
    script.set("clk_freq_mhz", 500)
    script.set_path("final_netlist_file", "build out/gcd final.v")
    script.set_list("lib_list", ["libs/fast corner.lib", "libs/slow.lib"])
    script.set_expr("clk_period_ps", "1000000.0 / $clk_freq_mhz")
    script.set_path("tmp_dir", "build out/tmp")
    script.file_mkdir(tcl.var("tmp_dir"))
    script.set_path("synth_stat_json", "reports/synth stat.json")
    script.set("stat_dir", tcl.call("file", "dirname", tcl.var("synth_stat_json")))

    with script.if_not(tcl.file_isdirectory(tcl.var("stat_dir"))):
        script.file_mkdir(tcl.var("stat_dir"))

    assert script.build() == (
        "# Auto-generated by RosettaKit\n"
        "set top_design gcd_core\n"
        "set clk_freq_mhz 500\n"
        "set final_netlist_file {build out/gcd final.v}\n"
        "set lib_list [list {libs/fast corner.lib} libs/slow.lib]\n"
        "set clk_period_ps [expr {1000000.0 / $clk_freq_mhz}]\n"
        "set tmp_dir {build out/tmp}\n"
        "file mkdir $tmp_dir\n"
        "set synth_stat_json {reports/synth stat.json}\n"
        "set stat_dir [file dirname $synth_stat_json]\n"
        "if {![file isdirectory $stat_dir]} {\n"
        "    file mkdir $stat_dir\n"
        "}\n"
    )


def test_tcl_quoting_covers_special_characters() -> None:
    script = tcl.Script()
    script.set("space", "a b")
    script.set("braces", "a}b")
    script.set("dollar", "cost $5")
    script.set("bracket", "pin[0]")
    script.set("quote", 'a"b')
    script.set("backslash", r"a\b")
    script.set("empty", "")

    assert script.build() == (
        "set space {a b}\n"
        "set braces a\\}b\n"
        "set dollar {cost $5}\n"
        "set bracket {pin[0]}\n"
        "set quote {a\"b}\n"
        "set backslash {a\\b}\n"
        "set empty {}\n"
    )


def test_tcl_validate_reports_contextual_diagnostics() -> None:
    script = tcl.Script()
    script.set_path("bad_path", "", origin="unit.empty_path")
    script.raw_line("puts $untrusted", origin="unit.raw")
    script.set("bad_list", tcl.list_value(["a", "b"]), origin="unit.list")

    diagnostics = script.validate()

    assert [(item.code, item.origin) for item in diagnostics] == [
        ("empty-path", "unit.empty_path"),
        ("unsafe-raw", "unit.raw"),
        ("list-through-scalar-api", "unit.list"),
    ]


def test_tcl_build_fails_for_invalid_or_unsafe_documents() -> None:
    invalid = tcl.Script()
    invalid.set("", "value", origin="unit.empty_name")
    with pytest.raises(ValidationError, match="tcl"):
        invalid.build()

    unsafe = tcl.Script()
    unsafe.raw_line("puts $untrusted", origin="unit.raw")
    with pytest.raises(UnsafeRawError, match="unit.raw"):
        unsafe.build()

    assert unsafe.build(allow_unsafe_raw=True) == "puts $untrusted\n"
