from __future__ import annotations

from pathlib import Path

from rosettakit import tcl


def build_global_var_tcl() -> str:
    script = tcl.Script()
    script.comment("Auto-generated by RosettaKit")
    script.set("top_design", tcl.word("gcd_core"))
    script.set("clk_freq_mhz", 500)
    script.set_path("final_netlist_file", "build out/gcd final.v")
    script.set_list("lib_list", ["libs/fast corner.lib", "libs/slow.lib"])
    script.set_expr("clk_period_ps", "1000000.0 / $clk_freq_mhz")
    script.set_path("tmp_dir", "build out/tmp")
    script.file_mkdir(tcl.var("tmp_dir"))
    script.set_path("synth_stat_json", "reports/synth stat.json")
    script.set("stat_dir", tcl.call("file", "dirname", tcl.var("synth_stat_json")))
    with script.if_not(tcl.file_isdirectory(tcl.var("stat_dir"))):
        script.file_mkdir(tcl.var("stat_dir"))
    return script.build()


def write_example(path: Path = Path("examples/out/yosys/global_var.tcl")) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_global_var_tcl(), encoding="utf-8")
    return path


if __name__ == "__main__":
    write_example()
